# Generated by Django 5.0.6 on 2024-12-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtus', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
