# Generated by Django 5.0.6 on 2024-12-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtus', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
