# Generated by Django 5.0.6 on 2024-12-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtus', '0006_userinfo_cartao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
